### ISSUE TITLE
Allow for millimeters in the length aggregation files in gadget.fit 

### ISSUE THREAD

**Issue by bthe** [bthe/rgadget#1]
Gadget.fit currently assumes that all lengths are in centimeters, making illustrations of fit for a model of shrimp less than ideal:)

**Comment by lentinj** [comment]
I'd assumed that lengths were in an arbitrary unit in GADGET files, rather than being explicitly defined to be centimetres. If all aggfiles in the model were in millimetres, would that be a problem?

Or do I not know what I'm talking about? :)

**Comment by bthe** [comment]
You are absolutely right, this is just a silly assumption that I made when I had to hand in a report based on the output from gadget.fit.

**Comment by bthe** [comment]
Coercion to integer removed from gadget.fit, works now as expected
