### ISSUE TITLE
gadget-course still uses suitability

### ISSUE THREAD

**Issue by lentinj** [bthe/rgadget#100]
I've had a bit more of a hack at compiling the course. This bit references suitability(), which got removed as part of the R check purge: https://github.com/Hafro/gadget-course/blob/master/day1_continued.Rmd#L234-L254

I can't see anything similar, should suitability() be restored for now? I guess the real answer would be to develop something better as part of #97 and then reference that.

**Comment by bthe** [comment]
Oh, had forgotten about that. I'm storing all the legacy functions in `gadgetsim`, as I think the simulator could have utility as a stand alone package. `gadgetsim` is still in progress and I don't think `Rgadget` should depend on `gadgetsim`, so I think we should for the time being we should just restore the function for now.

In general I think these functions that describe the population dynamics, such as predator suitability and growth, should be available to the user to test and visualize. Could that be linked to teh development of `gadget3`?

**Comment by lentinj** [comment]
> Could that be linked to teh development of gadget3?

Definitely. It'd be fairly easy to keep this interface, and use gadget3 components instead to generate R code instead of C++ for the suitability->matrix function and run it.
