### ISSUE TITLE
project multiple fleets

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#102]
It is unclear to me how projections can be implemented for multiple fleets.
The following
```
      ... %>%
      gadget_project_fleets(pre_fleet='comven1', fleet_type="linearfleet") %>% 
      gadget_project_fleets(pre_fleet='comven2', fleet_type="linearfleet") %>%
```
sets multiple fleetfiles correctly, but how to specify a grid with different combinations of harvest rates then? Intuitively I would do that with ```gadget_project_advice``` but it seems to deal only with vectors. Am I missing some functionality?

**Comment by bthe** [comment]
yes, this is bit unclear how you would do this. I had envisaged that you would apply `gadget_project_advice` for each fleet and supply a vector of harvest rates for each fleet and `gadget` would run a cartesian product of these harvest rates, provided that the latter call to `gadget_project_advice` has been supplied with a number of replicates that is the multiple of the number of replicates of the former call and length of the former effort vector. 

But if you want something different you could just edit parameters directly using the `wide_parameters` function.
