### ISSUE TITLE
gadget.iterative not working with Windows

### ISSUE THREAD

**Issue by mingsun** [bthe/rgadget#106]
The function "gadget.iterative" does not work on windows as forking in mclapply is not supported by windows.

I am wondering is there any way to modify or bypass this but still achieving the same purpose on windows?

**Comment by bthe** [comment]
Well, there are two ways of achieving this atm. The simplest, but slowest would be to run gadget.iterative in serial mode by setting the run.serial=TRUE. You could also try to implement what is suggested here https://www.google.com/amp/s/www.r-bloggers.com/parallelsugar-an-implementation-of-mclapply-for-windows/amp/ but note that this approach will sacrifice one core from your computer.
