### ISSUE TITLE
Check F calculations in gadget.fit and gadget_project_output

### ISSUE THREAD

**Issue by willbutler42** [bthe/rgadget#115]
gadget.fit and gadget_project_advice appear to calculate F differently. Pam noticed this for GSS.

**Comment by bthe** [comment]
It may be related to this commit https://github.com/gadget-framework/rgadget/commit/959721532c2b9b308e6ed427278d63ebf662fa24

**Comment by willbutler42** [comment]
Thanks, I'll test this and the prior version later
________________________________

**Comment by willbutler42** [comment]
The problem was that when f.age.range was specified, F was aggregated via a weighted mean in gadget and an unweighted mean in gadget.fit. This has been fixed in gadget_fit with the parameter "weighted.mortality" (commit 00994eb). If f.age.range is specified and weighted.mortlaity = TRUE, the output will match gadget.project.output. If weighted mortlaity = FALSE, the unweighted mean is calculated (as gadget.fit currently does).
