### ISSUE TITLE
Weights of likelihood components

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#14]
After fitting a model with gadget.fit() I got a file out$likelihoodsummary. Weights of likelihood component there are always 1. What does it mean? Should they always be 1 at that file?

**Comment by bthe** [comment]
The likelihoodsummary reports the weights that Gadget reads from the likelihood file used. The gadget.fit function uses the main file in the model directory, not main.final from WGTS, so if you likelihood file has one for all components then this will be reflected in the likelihoodsummary. But it it might be nicer to actually have the weights from the final run.
