### ISSUE TITLE
Slope of the fit

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#15]
I noticed that whether I select fixedslopeloglinear or loglinear fit to survey indices will influence my model a lot (age distribution, length distribution, etc.). How then to choose a fitting function? If the slope is estimated (in loglinear function), the values of it are very different. Some are close to one, while other are 0.5 or even 6.5. What those values really tell us? How should we select a value of the slope when choosing fixedslopeloglinear function?

**Comment by bthe** [comment]
This is a bit outside the scope of Rgadget and is a topic of many published papers. For Gadget models I would refer to Taylor et al 2007 for a discussion on the selection of these values and the effects of the various slopes in Gadget.
