### ISSUE TITLE
F=0 in the first years

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#17]
In most of the models the fit$res.by.year$F is zero for the first 2-3 years, despite there are catches.
Also the "mortality" reported in WGTS/out.fit/stockName.prey (which refers to fishing mortality as far as I understand) is different from zero.
Any suggestion?

**Comment by bthe** [comment]
I guess this is because you have 0 initial abundance your model for the first 2 - 3 years. gadget.fit will read the F from the maximum age unless instructed otherwise. You can change behaviour if you set the f-range in gadget.fit.

**Comment by vbartolino** [comment]
Found it thanks. Yes, specifying the f.age.range solve it
