### ISSUE TITLE
error with gadget.forward on multispecies model

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#18]
I'm trying 'gadget.forward' on a 3 species, 4 fleets model with some default values as follows:
`fwd <- gadget.forward(params.file="WGTS/params.final",
                                    years=10,
                                    fleets=data.frame(fleet=c('comm.act','comm.pas','comm.her','comm.spr'),
                                                                 ratio=c(1,1,1,1)),
                                    num.trials=10, effort=0.5, rec.window=2000:2012, stochastic=F)`

regardless the values I get the following error:
`Error in read.table(sprintf("%s/out/%s.lw", pre, x), comment.char = ";") : 
  no lines available in input
In addition: Warning messages:
1: In initialize(value, ...) : NAs introduced by coercion
2: running command 'gadget  -s    -i ./PRE/params.forward  -main ./PRE/main.pre         2>/dev/null' had status 1`

Thankful for any suggestion

**Comment by bthe** [comment]
Currently gadget.forward expects exactly one recruiting stock, the function needs to be rewritten to take this into account..

**Comment by bthe** [comment]
A complete rewrite of gadget.forward has now been published which now allows for multi-species stochastic forward simulations.
