### ISSUE TITLE
error with gadget.forward and normal condition distribution renewal

### ISSUE THREAD

**Issue by mmrinconh** [bthe/rgadget#21]
gadget.forward gives an error when the renewal is of the type normal condition distribution, to fix it temporarily it's necessary to remove two lines around lines 204 and add a new one as follows:

x@renewal.data <- rbind.fill(subset(x@renewal.data,
                  year < sim.begin), data.frame(year = rec.years,
                  step = tail(x@renewal.data$step, 1), area = tail(x@renewal.data$area,
                    1), age = tail(x@renewal.data$age, 1), number = sprintf("(\* 0.0001 #rec%s )",
                    rec.years), mean = tail(x@renewal.data$mean,
                    1), stddev = tail(x@renewal.data$stddev,
                    1), *\* #relcond = tail(x@renewal.data$relcond, 1),
        #alpha = tail(stocks$anch@renewal.data$alpha, 1),
                  #beta = tail(x@renewal.data$beta, 1),**
        stringsAsFactors = FALSE))

and also in the stockfile inside folder PRE,  to replace by hand normalparamfile by normalcondfile.

**Comment by bthe** [comment]
This is now possible with the most recent version of rgadget, give it a go and let me know.

**Comment by mmrinconh** [comment]
Hi, it doesn't work for me. The stock has only one recruitment season per year. In the stock file built inside PRE folder there is still this 'normalparamfile' linking to a normalcondfile recruitment file.  that could be the reason for the error.

  The error is the following:
       `prueba<-gadget.forward(params.file='WGTS/params.final',
         effort=seq(0.5,1.5,by = 0.05),
          fleets=data.frame(fleet = "seine", ratio = 0.6),
          years = 100,
           num.trials = 10, rec.window=c(2001,2015), gd = list(dir = ".", rel.dir = "PRE"))`

```
Error in read.table(sprintf("%s/out/%s.lw", pre, x), comment.char = ";") : 
  no lines available in input
In addition: Warning message:
running command 'gadget  -s    -i ./PRE5/params.forward  -main ./PRE5/main.pre         2>/dev /null'   had status 1 
```

``

**Comment by mmrinconh** [comment]
Hi, again with the last version of gadget.forward in the stock file built inside PRE folder there is still this 'normalparamfile' linking to a normalcondfile recruitment file. If I run line by line and replace manually 'normalparamfile' by 'normalcondfile' before callGadget line, it works!

**Comment by bthe** [comment]
The problem was in the stockfile write methods where a check for the dimension of the recruitment file was 
```
if(ncol(x@renewal.data==8)) 
```
where it should have been 
```
if(ncol(x@renewal.data)==8)
```
