### ISSUE TITLE
error gadget.fit with likelihood catchstatistics weightnostddev

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#22]
I use this LH for weight-at-age data.

```
> fit <- gadget.fit()
Joining by: c(".id", "length")
Joining by: c("year", "area", "fleet")
Warning message:
In FUN(X[[i]], ...) :
  Error in read.printfile -- Header could not be read from file WGTS/out.fit/wgtAtAge.comm
```

I think the reason is that the header made by Gadget in WGTS/out.fit/wgtAtAge.comm is:
`; year-step-area-age-number-mean[-stddev]`
and '-' within the last column gets confused in read.printfile

**Comment by bthe** [comment]
Done:)
