### ISSUE TITLE
suggestion on binding gadget runs

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#23]
This function bind different gadget runs ("most of the output") for easy comparison plot.
Gfit is a list of 2 or more gadget.fit-class objects:

``` r
gadget.bind <- function(Gfit, ...){
    out <- Gfit[[1]]
    out[] <- NA
    for(i in 1:length(out)){
        if(sum(class(Gfit[[1]][[names(out)[i]]]) == "list") == 1 &
           length(Gfit[[1]][[names(out)[i]]]) > 1){ NULL } else {
               tmp <- sapply(Gfit,function(x){x[names(out)[i]]})
               names(tmp) <- names(Gfit) # replace with readable run names
               out[[i]] <- bind_rows(tmp, .id="run")
        }}
    return(out)
}
```

This is an example of how to use it:

``` r
fitL <- gadget.bind(list(r16=fit16, r17=fit17, r18=fit18))
ggplot(fitL$res.by.year,aes(year,total.biomass)) +
    geom_line(aes(color=run)) +
    theme_bw() +
    ylab("TSB") +
    xlab('Year')
```

**Comment by bthe** [comment]
I'm testing a version of this currently:

> bind.gadget.fit <- function(...){
>  tmp <- 
>    list(...) %>% 
>    purrr::transpose() %>% 
>    purrr::map(~purrr::map_if(.,is.null,data.frame)) %>% 
>    purrr::map(~purrr::map_if(.,is.factor,as.character)) %>% 
>    purrr::map(purrr::safely(~dplyr::bind_rows(.,.id='model'))) %>% 
>    purrr::map('result')
>  class(tmp) <- c('gadget.fit',class(tmp))
>  return(tmp)
> }

**Comment by bthe** [comment]
This is now completed, you can now use bind.gadget.fit(fit1,fit2, ...)
