### ISSUE TITLE
Fleetfiles incorrectly imported by read.gadget.file 

### ISSUE THREAD

**Issue by bthe** [bthe/rgadget#24]
I stumbled upon an error when importing gadget fleet files using read.gadget.file. A typical fleet file looks like this

```
[fleetcomponent]
totalfleet              comm
livesonareas            1
multiplicative          1.0
suitability
codimm                  function exponential    #acomm (* 0.01 #bcomm)  0 1
codmat                  function exponential    #acomm (* 0.01 #bcomm)  0 1
amount                  Data/cod.fleet.data
```

Whereas the output from gadget.file is:

```
[fleetcomponent]
totalfleet  comm
livesonareas    1
multiplicative  1
codimm  function exponential    #acomm (* 0.01 #bcomm)  0 1
codmat  function exponential    #acomm (* 0.01 #bcomm)  0 1
amount  Data/cod.fleet.data
```

Note the missing suitability line.

**Comment by lentinj** [comment]
Okay, figured this out.

Does a fleetfile have multiple fleets in, or do you have multiple fleet files if you want multiple fleets, or can you do either with no real difference in end result? The user guide isn't very clear.

**Comment by lentinj** [comment]
(answered my own question by looking at the model examples I have.)

**Comment by lentinj** [comment]
So I can at least preserve the suitability now, but the components are `[fleetcomponent]` first, then `suitability`, which is a bit rubbish, they should be nested to make any reasonable sense. Will look into it.

**Comment by lentinj** [comment]
See https://github.com/Hafro/rgadget/pull/30
