### ISSUE TITLE
catchinkilos LH weight = 1

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#25]
I've a model implemented with a linearfleet and effort data, and a 'catchinkilos' likelihood component.

The gadget.iterative always returns weight = 1 for the 'catchinkilos' likelihood component.
In practice I do not get this component weighted, but checking the model I cannot really figure out why (no warning or error is reported and all files seem in place).

Could it be related to gadget.iterative?

**Comment by bthe** [comment]
This is one of the likelihood components that is on the exclusion list for the reweighting, along with boundpenalty and understocking. Main reason for this is that when catches are down-weighted the model will happily assign random catches to help with the fit of the up-weighted dataset, and you may easily end up in the case where the catches are not considered at all or the weight is so high that you run into optimization issues.

**Comment by vbartolino** [comment]
Crystal clear! Thanks.
