### ISSUE TITLE
gadget.forward customize seasonal pattern and species specific parameters

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#26]
There are two groups of features which I haven't been able to find in 'gadget.forward' but which would be relevant.

1) specify the seasonal pattern in the effort of the fleet. Ideally, the most flexible setting would be to give the user the freedom to specify the fleet.ratio for all combinations of fleet, year, timestep

2) arguments like rec.window and mat.par should accept stock specific input

**Comment by bthe** [comment]
This can hopefully be achieved with the most recent version of gadget.forward, you should be able to pass a data.frame for both rec.window (with columns stock, upper and lower) and fleets with additional columns years and/or steps. Mat.par is no longer a part of the input to the function. Feel free to try it out..
