### ISSUE TITLE
Recursively reading gadget files

### ISSUE THREAD

**Issue by lentinj** [bthe/rgadget#29]
Recursively read everything in a model (i.e. so reading a mainfile will read everything).

Don't worry about file pointers, if the whole thing doesn't fit in memory then you can't run the Gadget model anyway.

**Comment by lentinj** [comment]
Headaches here:
- Will need a regex of keys that could contain file names, `files?$|^amount$` should work.
- Some mainfile properties have multiple files, e.g. `stockfiles    codimm  codmat`. Currently we represent the value here as `c('codimm', 'codmat')`. We can't have a vector of 2 gadgetfiles. I think this is only a mainfile issue, so could have something else to read this and use a different representation.

**Comment by bthe** [comment]
I can't remember any place where you have two files being read at once in any other file than the main file. 
However this can occur when you read in model variable files (time and stock variables), so variables read in need to be screened. But I guess this could be done on a case by case basis when we try to evaluate a gadget formula.

**Comment by lentinj** [comment]
I looked through all the example files I had and the user guide, and couldn't find anything either.

And yes, being part of a gadget formula will be different anyway, so that should be fine.

**Comment by lentinj** [comment]
There's a branch that does this here https://github.com/lentinj/rgadget/tree/recursive-reads however I want to get model variants done too before a pull request.
