### ISSUE TITLE
plot the estimated age composition of the stock

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#3]
I use the function below as follows:
stockDistr.plot(data=read.printfiles("WGTS/out.fit/")$sprat.std, ages=1:8, plusGroup=T, lines=F)
### Plot the estimated age structure of the stock

stockDistr.plot <- function(data, ages, plusGroup=T, step=1, area=1, lines=F){

 # data - data.frame with the columns 'number', 'age', 'year'
 # ages - vector with ages to plot
 # step - specify the step to plot (only one at a time), default = 1
 # area - vector with the areas to sum across, default = 1
 # plusGroup - if the last year is a plusGroup
 # lines - add lines to follow individual cohorts

```
require(RColorBrewer)

data <- data[data$step==step & data$area %in% area,]
adist <- tapply(data$number, list(data$year, data$age), sum)

if(plusGroup==TRUE){
    tmp <- adist[,which(colnames(adist) %in% ages[length(ages)]):dim(adist)[2]]
    tmp <- apply(tmp,1,sum)
    adist <- adist[,which(colnames(adist) %in% ages)]
    adist <- cbind(adist[,-dim(adist)[2]], tmp)
    colnames(adist) <- ages
    colnames(adist)[dim(adist)[2]] <- paste(colnames(adist)[dim(adist)[2]], "+",sep="")}
if(plusGroup==FALSE){
    adist <- adist[,which(colnames(adist) %in% ages)]} else {}

col.pal <- brewer.pal(11,"Spectral")
col.pal <- rep(col.pal,4)

age <- colnames(adist)
yr <- rownames(adist)
xx <- seq(0.75, 0.75+(1+0.2)*(length(yr)-1), 1+0.2) # x unit needed in barplot to account for inter-bar space

par(mfrow=c(length(age),1), mai=c(0.1,0,0,0),omi=c(0.5,0.5,0.1,0.1))
for(a in 1:length(age)){
    barplot(adist[,a],xaxt="n",col=col.pal[10:31-a], space=0.2)
    if(lines==TRUE){
        for(i in 1:length(xx)){
            lines(c(xx[i]-0.5,xx[i]+0.5),c(max(adist[,a]),0), col="grey")
        }
    } else {}
    legend("topright",paste("Age",age[a]), bty="n",cex=1.5)
}
axis(1,xx,yr)
mtext("Year", 1, line=2, outer=T)
mtext("Number of fish", 2, line=2.5, outer=T)
```

}

![adist stock](https://cloud.githubusercontent.com/assets/9845667/8305989/679b8c98-19b4-11e5-85cd-cf3382754d00.png)

**Comment by bthe** [comment]
Looks good, this could be easily incorporated into plot.gadget.fit

**Comment by bthe** [comment]
And finally I did, you can now do: 

fit <- gadget.fit()
plot(fit, data='stock.std')
