### ISSUE TITLE
read.gadget.file to read gadget output

### ISSUE THREAD

**Issue by bthe** [bthe/rgadget#31]
Gadget models have three types of output files:
- Model output (e.g. likelihood prediction, biomass by year, step, age etc) 
- Likelihood output (values of parameters and likelihood components)
- parameter files (both in wide and long format)

A model output file is created with a specific printfile and is of the form preamble, tabular data and in the case of survey indices a postamble

```
; Gadget version 2.2.00-BETA running on ComputerName Wed Apr 27 22:03:35 2016
; Likelihood output file for the likelihood component si.F.20-50
; year-step-area-label-number
1997    4          1      len10    6687762.6
....
2015    4          1      len10     30062.25
; Regression information for area 1
; len10 intercept 6.805886 slope -5.3238671e-10 sse 1e+10
```

Here you want the tabular data to be read as a data.frame, names of columns read from the preamble and the information from the postamble and joined with the table. The postamble can include one or more regression results, i.e. the length of the postamble is 2*unique(label) lines. 

The likelihood output files has three components, first a listing where the variable occurs, second the likelihood components names, type and weights, and third table of the likelihood function values (total and each component) along with the parameter values. The file is created using:
`gadget -s -i params.in -o lik.out`

```
; Gadget version 2.2.00-BETA running on ComputerName Sat Jun 11 17:00:34 2016
; Listing of the switches used in the current Gadget run
Linf    codimmgrowergrowthcalcHmodelvariable   
....      
;
;
; Listing of the likelihood components used in the current Gadget run
;
; Component     Type    Weight
matp.igfs       6       48.095
alkeys.aut      3       33599.6
alkeys.comm     3       16937.3
alkeys.igfs     3       35086.4
ldist.aut       3       35162.7
ldist.comm      3       23701.9
ldist.igfs      3       30961.6
si.gp1  1       7.1061
si.gp1a 1       1.08626
si.gp2  1       29.1428
si.gp2a 1       2.40657
si.gp3  1       85.0689
si.gp3a 1       100
understocking   2       100
bounds  8       10
;
; Listing of the output from the likelihood components for the current Gadget run
;
0              160         90          6          1       1000         35         25         15          7          7          5          5         70         70          1          1         50         50         40         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         30         25         10         10        -10         19         -4          9         -4          9               328.9    10.02    17.34    27.55    5.653    38.11     22.4    24.14     15.1    7.866    1e+10    2.352    2.783 1.22e+18        0          1.21991794478447e+20
```

The third format is gadget parameter files which has format very similar to the gadget output files. 
These outputs files are not currently handled correctly by `read.gadget.file`, as they are mainly tabular. Currently these files are read in using `read.printfiles`, `read.gadget.lik.out` and `read.gadget.parameters` but ideally `read.gadget.file` should digest all of these.

**Comment by lentinj** [comment]
Is there scope for changing the format of the output files so we could meet somewhere in the middle? It's less risky in comparison to changing model inputs, since you're unlikely to store very old model runs then want to parse them. You'd just re-run with the newest Gadget.

In particular, looking at the examples above:
- Change "year-step-area-label-number" to be tab-separated
- Add a "; -- data --" before data.frame components

That said there's there's still changes needed. `read.gadget.file` currently uses `read.table` when there's a data.frame to read, which will just read to the end of the file. To read 2 data.frames, it'll have to read the whole data.frame into memory first, then hand that to `read.table`. Annoying but not the end of the world.

Also the final comments will need attaching somewhere. A "postamble" attribute would do the trick.

**Comment by bthe** [comment]
I certainly think that is reasonable to change the output from Gadget as you suggest, and adding a ; -- data -- switch should be safe.

I think it would also be useful to have a function that can handle tables with gadget formulae.
