### ISSUE TITLE
does gadget.forward accept seasonal recruitments?

### ISSUE THREAD

**Issue by MarcoEnea** [bthe/rgadget#33]
When running gadget.forward (with last Rgadget version installed) on a model assuming seasonal recruitments I get the following error:  

> fit.forward <- gadget.forward(years = 11, num.trials = 101,
>                                                   fleets = data.frame(fleet = c("commBMT","TUNcommBMT","survey"),
>                                                   ratio = c(1,1,1)), effort = 0.62, stochastic = TRUE, 
>                                                   rec.window = 2002:2014)

Errore: wrong result size (44), expected 176 or 1

This does not happen for a model assuming annual recruitments.

**Comment by vbartolino** [comment]
A couple of comments from my limited experience using 'gadget.forward':
- under 'fleets' I only specify the commercial fleets (although I do not think that is a problem)
- I always add the argument rec.scalar where I specify a scalar for the recruitment of every species-year in the model

In my model recruitment is in only 1 timestep per year. Not sure if that could be the problem for a species like hake where I suppose you have recr in at least 2 different quarters

**Comment by bthe** [comment]
Seasonal (i.e. multi-step) recruitments is half way implemented at the moment, i.e. the code sort of allows it but the interface is not there yet. Currently the implementation could go two ways:
- The code guestimates the seasonal variations from historical recruitment patterns
- The user supplies the recruitment schedule

Or a combination of both these approaches. 

Regarding the call to gadget.forward I think it can actually lead to disastrous results to have the survey with an effort of 0.62 of its harvestable biomass, as the selection of the survey is often towards the smaller fish.

**Comment by bthe** [comment]
I just added an experimental functionality to `gadget.forward` that allows the user to supply a function which generates future recruitment. This should allow for seasonal recruitment.

**Comment by MarcoEnea** [comment]
Thanks Bjarki,
I’ll give a look at it.
Bye, 
Marco
