### ISSUE TITLE
Multi-area models -- Error with gadget.iterative

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#35]
When running multi-area model with gadget.iterative I got an error: 
`*** Error in`gadget': free(): invalid next size (fast): 0x0000000000d5d5f0 ***`
Run continued though after the error, but at the end all files in WGTS folder starting with lik. or params. were empty.

**Comment by bthe** [comment]
Is this an issue with gadget proper, what happens when you just run:

```
gadget -s -i params.in
```

**Comment by nataliia-kulatska** [comment]
Simulation works, just with 40 warnings (like in log linear regession - received invalid values, catchdistribution - fleet not defined on all areas)

**Comment by nataliia-kulatska** [comment]
And also what does this warning from simulation mean?

`in file Modelfiles/fleet - Note that this exponentiall50 has had a factor of 4 removed from the source code`

**Comment by pfrater** [comment]
I'm guessing that your params file has values that don't seem to match well with your stocks? Maybe try tweaking values in your params.in file.

As for the error, if you look at the source code (suitfuncptrvector.cc, line 66), this is just a standard error written to the screen when the exponentiall50 suitability function is chosen. I'm guessing it was updated at some time and changed from an older version, and the error is just to alert users of the change. I could be wrong, though.

**Comment by bthe** [comment]
Sorry, but I think it is probably more relevant to run:

```
 gadget -s -i WGTS/params.final -main WGTS/main.print
```

Does that work?

Regarding the warning, it is exactly as @pfrater suggested and it will be removed in the next iteration of gadget.

**Comment by nataliia-kulatska** [comment]
Unfortunately I cannot run 
`gadget -s -i WGTS/params.final -main WGTS/main.print`
since params.final is empty. However I changed the setting of the model, so survey indices from different areas of the same length group are in the same file (in previous run areas were in separate files). Now gadget.iterative finished without an error, but gadget.fit got one:

`Error in (x + 2):(x + tyler - 1) : NA/NaN argument` 

Running `gadget -s -i WGTS/params.final -main WGTS/main.final` now brings a new warning `Warning in migration - value outside bounds -0.499969` Can this be a reason of error with gadget.fit?

**Comment by bthe** [comment]
These are most likely two separate issues, but I would actually worry about the migration values. Did you set up the migration penalty function properly?

**Comment by nataliia-kulatska** [comment]
No, I didn't know about this function. So, unfortunately I haven't specified it at all. I am trying the run with this function now.

**Comment by nataliia-kulatska** [comment]
Setting migration penalty function helped to get rid of the migration warning, however error in gadget.fit persist.

**Comment by nataliia-kulatska** [comment]
I detected when this error arise (`Error in (x + 2):(x + tyler - 1) : NA/NaN argument`)

It's when there is only one component in migration matrix. 

This will get an error:
[migrationmatrix]  
name    feeding.im
1   2   #fd2
1   3   #fd2
2   1   #fd2
2   3   #fd2
3   1   #fd2
3   2   #fd2

This, won't:
[migrationmatrix]  
name    feed
2   1   #fd
3   1   #fd
;
[migrationmatrix]  
name    feeding.im
1   2   #fd2
1   3   #fd2
2   1   #fd2
2   3   #fd2
3   1   #fd2
3   2   #fd2

**Comment by bthe** [comment]
This is a bug in Gadget (proper) and is referred to here https://github.com/Hafro/gadget/issues/8
