### ISSUE TITLE
Multi-area models -- problem with gadget.fit

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#37]
I have a 3-area model, and recruitment is in each of the areas (in recruitment file each year-area combination has it's own parameter value). However something went wrong after using gadget.fit():

`head(fit$res.by.year[fit$res.by.year$stock=="codim",])`

   year  stock  area    catch        num.catch       F           total.number total.biomass
4 1974 codim  area1  29463112   30475039  0.5114301    366729520      91762669
5 1974 codim  area1  29463112   30475039  0.5114301    366729520      91762669
6 1974 codim  area1  29463112   30475039  0.5114301    366729520      91762669
7 1974 codim  area2  21673890   22514621  0.3737798    360020534      94085918
8 1974 codim  area2  21673890   22514621  0.3737798    360020534      94085918
9 1974 codim  area2  21673890   22514621  0.3737798    360020534      94085918
  harv.biomass ssb   .id      recruitment
4            0         0  codim   138727350
5            0         0  codim   278095920
6            0         0  codim   269194550
7            0         0  codim   138727350
8            0         0  codim   278095920
9            0         0  codim   269194550

Since, number of rows for immature cod got tripled and recruitment value is not unique for year-area combination, but rather for the year and row position.

**Comment by pfrater** [comment]
Something likely went wrong in gadget.fit() when the res.by.year and stock.recruitment tables were merged together. If you View(gadget.fit) and go to line 166 you'll see that these tables get merged by year and stock and that everything from the res.by.year table is kept (and also gets multiplied if merged with the stock recruitment and there is something missing there) My guess is that there's a slight error with something in the stock recruitment file. Perhaps check that. Are areas listed in that file?

**Comment by nataliia-kulatska** [comment]
Thanks Paul, I have areas specified in the recruitment data file. But you were right to pinpoint me to look on the source code of gadget.fit. I found that line 
`res.by.year <- merge(res.by.year,stock.recruitment,all.x = TRUE, by=c('year','stock'))` 
So area is not taken into account when the two tables are merged. That's why rows got tripled in the case of 3 areas.

**Comment by pfrater** [comment]
Maybe...possibly. I'm not sure, but it should be fairly easy to load the stock.recruitment file manually and see what it looks like. Try this:

`main <- read.gadget.main('path/to/your/mainfile')`
`stocks <- Rgadget:::read.gadget.stockfiles(main$stockfiles)`
`params <- read.gadget.parameters('path/to/params/file') #likely WGTS/params.final`
`stock.recruitment <- Rgadget:::get.gadget.recruitment(stocks, params)`

Then you can see what the recruitment file looks like in R. Tracing the res.by.year table back is a bit more difficult.

**Comment by nataliia-kulatska** [comment]
Unfortunately received an error 

```
Error in FUN(X[[i]], ...) : 
  trying to get slot "doesrenew" from an object of a basic class ("list") with no slots
```

**Comment by pfrater** [comment]
You're getting this in the last line? (stock.recruitment <- Rgadget:::get.gadget.recruitment(stocks, params)). Your 'stocks' object should be a list of 'gadget-stock' objects. If you have 2 stocks, say codim and codmat, then there should be 2 objects of class 'gadget-stock' in the list. Check 

`str(stocks)`

and then 

`str(stocks$codim) #or whatever the name of your particular stock is`

**Comment by nataliia-kulatska** [comment]
I couldn't use read.gadget.stockfiles, since it said:
`Error: could not find function "read.gadget.stockfiles"`

So I used `read.gadget.file('path/to/file','name_of_the stock_file',file_type='stock')`

But it should be the same, right?

So I read only immature stock there, since only it renew. I also check this code with previous models (which didn't had any problems) and got the same error

**Comment by nataliia-kulatska** [comment]
And the stock file is a list with "doesrenew" part also being a list:
$ doesrenew          :List of 4
  ..$ doesrenew      : num 1
  ..$ minlength      : num 3
  ..$ maxlength      : num 39
  ..$ normalparamfile: chr "Modelfiles/cod.rec"
  ..- attr(*, "preamble")=List of 1
  .. ..$ : chr "Recruitment"

**Comment by pfrater** [comment]
Sorry, my fault, you should use `stocks <- Rgadget:::read.gadget.stockfiles`. Make sure there are 3 colons there. I've updated this in the above code. Try it now.

**Comment by nataliia-kulatska** [comment]
Thank you a lot, it's working now. However the table I got doesn't have area column:

```
.id stock year recruitment
```

1   cod   cod   NA          NA
2 codim codim 1974   138727350
3 codim codim 1975   265353090
4 codim codim 1976   267696020
5 codim codim 1977   245843030
6 codim codim 1978   232538040

**Comment by nataliia-kulatska** [comment]
If I compare the values to those that I had in res.by.year they are the same values but with peculiar pattern. There I was having triplets of values repeated 3 times. So if I compare values from new table to its position in triplet in res.by.year:

Year    Position
1974    1
1975    2
1976    3
1977    3
1978    3
1979    3
1978    3
1979    3
1980    3

My guess is that position in triplet correspond to the area number.

**Comment by pfrater** [comment]
Did you ever get this resolved? Apologies for not responding. I was gone on a long weekend.

**Comment by nataliia-kulatska** [comment]
No, unfortunately I didn't. But I still believe that it's because area column is excluded when tables are merged:

`res.by.year <- merge(res.by.year,stock.recruitment,all.x = TRUE, by=c('year','stock'))`

**Comment by bthe** [comment]
https://github.com/Hafro/rgadget/pull/45 this should fix this..
