### ISSUE TITLE
gatget.fit error

### ISSUE THREAD

**Issue by GeoTuxMan** [bthe/rgadget#38]
After I run gadget.iterative(): 
`> tmp <- gadget.iterative(rew.sI=TRUE,  grouping=list(SI=c('cpue','cpue2',                                      'biomass','biomass2')))

Joining by: comp
[1] "Running final"
[1] "Comp final completed"`
,

I run gadget.fit():
`> fit <- gadget.fit()

Joining, by = c(".id", "length")
Joining, by = c("year", "area", "fleet")
Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns`

So, why do I get that error ?

**Comment by pfrater** [comment]
This is happening within `gadget.fit()` when it is combining datasets using the `merge()` function. It does this in several places, so could be any number of things. The `merge()` function spits that error when it is trying to combine data.frames that do not have similar column names, so I'd go through and check your output files to look for inconsistencies.

**Comment by GeoTuxMan** [comment]
OK, thanks very much.
I run again on other PC, and now it's ok, I don't have that error.
But, I have a new error:
`>prognFmax <- gadget.forward(years=7,params.file='WGTS/params.final',effort=0.2)`
Error in checkAtAssignment("gadget-stock", "renewal.data", c("tbl_df",  : 
  c("assignment of an object of class “tbl_df” is not valid for @‘renewal.data’ in an object of class “gadget-stock”; is(value, \"data.frame\") is not TRUE", "assignment of an object of class “tbl” is not valid for @‘renewal.data’ in an object of class “gadget-stock”; is(value, \"data.frame\") is not TRUE", "assignment of an object of class “data.frame” is not valid for @‘renewal.data’ in an object of class “gadget-stock”; is(value, \"data.frame\") is not TRUE")

**Comment by bthe** [comment]
Is this still a problem, I think the recent updates fix this problem
