### ISSUE TITLE
gadget.iterative, 'error all connections are in use'

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#42]
I have problem to run 'gadget.iterative' more than once in the same session and I start to get the following error:

`Error in file(con, "r") : all connections are in use`

Then a new R session is required.

**Comment by bthe** [comment]
Usually `closeAllConnections()` does the trick. This is however a fairly unexpected error `gadget.iterative`, what are you doing before running it?

**Comment by vbartolino** [comment]
After running a model with many likelihood components `showConnections(all=T)` returns a long list of connections. By running `gadget.iterative` more than once this list rapidly increases causing the problem above.
As you suggested `closeAllConnections()`does the trick (and solves the problem on my specific case).
