### ISSUE TITLE
Length distribution  of survey is not predicted in multi-area model

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#44]
Length distribution from survey are only predicted in one area but not the others (despite of present observation data and catch data in that areas for the survey fleet): column predicted in those are all NAs, number.y and total.pred are all 0s.

**Comment by pfrater** [comment]
Could you be a little more specific and perhaps share some snippets of the data? I assume this is in the catchdist.fleets data using gadget.fit?

**Comment by bthe** [comment]
I assume this is due to the fact the model doesn't predict catches of fish for that area/stock/fleet/step/year combination. This could be due to a number of things, have you looked at the fleet selection or migration?

**Comment by nataliia-kulatska** [comment]
Survey fleet selection seems to be fine, as for migration, other fleets catch fish in those areas, so I guess it's also fine.

Please see two summaries below to illustrate the issue:

`summary(fit$catchdist.fleets[fit$catchdist.fleets$name=="ldist.bits1" & fit$catchdist.fleets$area=="area1",])[, c(9:16)]`

![selection_048](https://cloud.githubusercontent.com/assets/16099366/17803760/a569aa3c-65f8-11e6-9d7e-78e30dacb702.png)

`summary(fit$catchdist.fleets[fit$catchdist.fleets$name=="ldist.bits1" & fit$catchdist.fleets$area=="area2",])[, c(9:16)]`

![selection_049](https://cloud.githubusercontent.com/assets/16099366/17803803/eb568aa6-65f8-11e6-9610-e773b874a52f.png)

**Comment by bthe** [comment]
If other fleets produce output which is captured by gadget.fit then I'm certain this is a model issue not an Rgadget issue. Just to be sure can you check the printfile, the fleet amounts file and the output in (e.g WGTS/out.fit/ldist.bits).

**Comment by nataliia-kulatska** [comment]
In printfile area1 has values, while area 2 and 3 only 0s.

**Comment by bthe** [comment]
Then you need to look into how the model behaves in those areas.
