### ISSUE TITLE
Error after Rgadget update

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#47]
Hi,

I updated Rgadget to version 0.5. Now I get the error with gadget.iterative:
`Error: Each variable must be named.
Problem variables: 5`

> traceback()
> 35: stop(..., call. = FALSE, domain = NA)
> 34: stopc(problem, ".\n", "Problem variables: ", format_n(vars))
> 33: invalid_df("Each variable must be named", x, which(bad_name))
> 32: check_tibble(x)
> 31: list_to_tibble(x, validate, raw_rownames(x))
> 30: as_data_frame.data.frame(data)
> 29: as_data_frame(data)
> 28: tbl_df(.data)
> 27: filter_(tbl_df(.data), .dots = dots)
> 26: as.data.frame(filter_(tbl_df(.data), .dots = dots))
> 25: filter_.data.frame(.data, .dots = lazyeval::lazy_dots(...))
> 24: filter_(.data, .dots = lazyeval::lazy_dots(...))
> 23: dplyr::filter(., year %in% year_range)
> 22: function_list[[k]](value)
> 21: withVisible(function_list[[k]](value))
> 20: freduce(value, `_function_list`)
> 19: `_fseq`(`_lhs`)
> 18: eval(expr, envir, enclos)
> 17: eval(quote(`_fseq`(`_lhs`)), env, env)
> 16: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 15: dat %>% dplyr::filter(year %in% year_range)
> 14: .fun(piece, ...)
> 13: (function (i) 
>     {
>         piece <- pieces[[i]]
>         if (.inform) {
>             res <- try(.fun(piece, ...))
>             if (inherits(res, "try-error")) {
>                 piece <- paste(utils::capture.output(print(piece)), 
>                     collapse = "\n")
>                 stop("with piece ", i, ": \n", piece, call. = FALSE)
>             }
>         }
>         else {
>             res <- .fun(piece, ...)
>         }
>         progress$step()
>         res
>     })(1L)
> 12: .Call(loop_apply_, as.integer(n), f, env)
> 11: loop_apply(n, do.ply)
> 10: llply(.data = pieces, .fun = .fun, ..., .progress = .progress, 
>         .inform = .inform, .parallel = .parallel, .paropts = .paropts)
> 9: dlply(x, "name", read.func)
> 8: .fun(piece, ...)
> 7: (function (i) 
>    {
>        piece <- pieces[[i]]
>        if (.inform) {
>            res <- try(.fun(piece, ...))
>            if (inherits(res, "try-error")) {
>                piece <- paste(utils::capture.output(print(piece)), 
>                    collapse = "\n")
>                stop("with piece ", i, ": \n", piece, call. = FALSE)
>            }
>        }
>        else {
>            res <- .fun(piece, ...)
>        }
>        progress$step()
>        res
>    })(2L)
> 6: .Call(loop_apply_, as.integer(n), f, env)
> 5: loop_apply(n, do.ply)
> 4: llply(.data = pieces, .fun = .fun, ..., .progress = .progress, 
>        .inform = .inform, .parallel = .parallel, .paropts = .paropts)
> 3: dlply(subset(likelihood$weights, !(type %in% c("penalty", "understocking", 
>        "migrationpenalty"))), "type", function(x) dlply(x, "name", 
>        read.func))
> 2: read.gadget.data(likelihood, year_range = time[[1]]$firstyear:time[[1]]$lastyear)
> 1: gadget.iterative(rew.sI = TRUE, grouping = list(sind.1.1 = grep("bits1", 
>        lik$surveyindices$name, value = TRUE), sind.4 = grep("bits4", 
>        lik$surveyindices$name, value = TRUE), surveyQ1 = c("ldist.bits1", 
>        "alk.bits1"), surveyQ4 = c("ldist.bits4", "alk.bits4"), catch.a = c("ldist.comm.active"), 
>        catch.p = c("ldist.comm.passive"), catch = c("adist.comm")), 
>        params.file = "params.base", wgts = "WGTS")

I tried few different models and all of them got an error.

**Comment by bthe** [comment]
This error is related to reading input data to Gadget into R. Try the following:

```
lik <- read.gadget.likelihood('likelihood')
lik.dat <- read.gadget.data(lik)
lik.dat.res <- read.gadget.data(lik,year_range=1990:1995)
```

If this is related to last update only the second data call will break. If that is the case look at lik.dat$data and look at the column names that are generated for the input data.

**Comment by nataliia-kulatska** [comment]
it was only `lik.dat.res` part that broke. Column names are next:

```
head(lik.dat$dat)
$catchdistribution
$catchdistribution$adist.comm
     length year step  area  age      number lower upper
```

**Comment by bthe** [comment]
I'll need to see all the column names and the first few entries to the data.

**Comment by nataliia-kulatska** [comment]
Seems that the problem is in catch in kilos likelihood. All other looks fine

```
> head(lik.dat$dat$catchinkilos$catch.act.like, 3)
[1] year    area    fleet   biomass <NA>   
<0 rows> (or 0-length row.names)
```

```
> head(lik.dat$dat$catchdistribution$adist.comm, 3)
  length year step  area  age   number lower upper
1    all 1974    1 area1 age1        1     1   137
2    all 1974    1 area1 age2  1768860     1   137
3    all 1974    1 area1 age3 19628600     1   137
```

```
> head(lik.dat$dat$stockdistribution$mat.bits1, 3)
  length year step  area stock age number lower upper
1  len10 1978    1 area1 codim all      4     9    11
2  len10 1978    1 area1   cod all      1     9    11
3  len10 2009    1 area1 codim all      2     9    11
```

```
> head(lik.dat$dat$surveyindices$bits1.20_40.like, 3)
  length year step  area   number lower upper
1  len40 1976    1 area3 12907.60    20    40
2  len40 1978    1 area1 11542.93    20    40
3  len40 1978    1 area2 15081.40    20    40
```

**Comment by bthe** [comment]
Aaa.. there is the culprit. I've hacked read.gadget.data to allow for varying number of columns in the catchinkilos likelihood component, give that a go. However there should be data read in for catch.act.like, are you sure it is set up correctly?

**Comment by nataliia-kulatska** [comment]
Thanks, Bjarki. It's working now.
