### ISSUE TITLE
scatterplot obs vs pred survey indices

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#5]
# simple scatterplot of obs vs. pred survey indices.

This how I use it:
surveyIndex.plot(data=fit, yearLab=TRUE, cex=0.8)

surveyIndex.plot <- function(data, h=TRUE, yearLab=FALSE, ...){
    ## data:     gadget.fit object returned from 'fit.gadget()'
    ## h:        horizontal orientation of the multi-panel plot
    ## yearLab:  replace dots with year labels

```
surv <- sort(unique(data$sidat$name))
par(mfrow=panel.size(length(surv),h=h), oma=c(1,1,0.2,0.2)) # see additional function below

# not sure why $acoustic and $number.x are distinct (this merges the two columns)
data$sidat$number.x <- ifelse(is.na(data$sidat$number.x), data$sidat$acoustic, data$sidat$number.x)

for(i in 1:length(surv)){
    tmp <- data$sidat[data$sidat$name==surv[i],]
    plot(tmp$number.x, tmp$predict, type="n", xlab="Observed", ylab="Predicted", main=surv[i])
    if(yearLab==FALSE){
        points(tmp$number.x, tmp$predict, ...)}
    if(yearLab==TRUE){
        text(tmp$number.x, tmp$predict, substring(tmp$year,3,4), ...)}
}}
```
# automatically define multi-panel size (nx,ny)

panel.size <- function(n, h=TRUE){
 # n = number of panels to plot
 # h = T  (nx<=ny)
    if(h==TRUE){
        out <- c(ceiling(n/sqrt(2_n)), floor(sqrt(2_n)))
    } else {
        out <- c(floor(sqrt(2_n)), ceiling(n/sqrt(2_n)))}
    if(out[1] \* out[2] < n){
        out <- c(ceiling(n/sqrt(2_n)), ceiling(sqrt(2_n)))
    } else {NULL}
    out  
}

![si_bias_v3](https://cloud.githubusercontent.com/assets/9845667/8325409/b9b193d8-1a59-11e5-8746-51d8bc1f2103.png)

**Comment by bthe** [comment]
There are two issues here:
- sidat from gadget.fit appears to be inconsistent between SI types
- Add these plots to the plot.gadget.fit function

**Comment by bthe** [comment]
Done, do:
fit <- gadget.fit()
plot(fit,type='x-y')
