### ISSUE TITLE
Possible typo in fishing mortality by year output from gadget.fit function

### ISSUE THREAD

**Issue by mmrinconh** [bthe/rgadget#53]
Hi, I think that there is a typo in line 149 of gadget.fit function, the line says:
`f.age.range <- c(max(out[[sprintf("%s.prey", 
                    x)]]$age), max(out[[sprintf("%s.prey", x)]]$age))`
and perhaps it should be:
`f.age.range <- c(min(out[[sprintf("%s.prey", 
                    x)]]$age), max(out[[sprintf("%s.prey", x)]]$age)),`

**Comment by bthe** [comment]
No, this is actually meant to select the fishing mortality at the modeled maximum age.
