### ISSUE TITLE
fleet.info missed multiplier and linearfleet

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#54]
There are two separate issues here:

1) `fit$fleet.info` does not account for the argument `multiplicative` in the fleetfile

2) when I use a linearfleet the catch amount in `fit$fleet.info` does not correspond to the catch amount in `fit$res.by.year`

**Comment by bthe** [comment]
This is now fixed with https://github.com/Hafro/rgadget/commit/329967f313fd89873ac33e8a089d58c080952854
