### ISSUE TITLE
error with updated gadget.forward

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#55]
I have updated Rgadget and I'm having problem in running 'gadget.forward' on previous models and codes:

```
Joining, by = "stock"
Error in if (!is_readable(full_path)) return(NULL) : 
  argument is of length zero
In addition: Warning message:
In left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y) :
  joining factor and character vector, coercing into character vector```

**Comment by GeoTuxMan** [comment]
Hi Valerio,

I have the same error, after I have updated Rgadget:

> prognFmax <- gadget.forward(years=7,params.file='WGTS/params.final',
+                             effort=0.2)
Error in if (!is_readable(full_path)) return(NULL) : 
  argument is of length zero

You figure out how to get rid of that error ?

**Comment by vbartolino** [comment]
Unfortunately, I haven't sorted this out by myself yet. At the moment I downgraded to the previous version of Rgadget, but it would be nice to have this solved to be able to use the most updated version of gadget.forward

**Comment by bthe** [comment]
My last commit should fix this..

**Comment by vbartolino** [comment]
The error is disappeared if ```custom.print=NULL``` and the function has the normal correct behaviour, but I get an error as soon as I provide a customized printfile.
```
> traceback()
3: stop("File ", variant_dir, file_name, " does not exist")
2: read.gadget.file(".", custom.print)
1: gadget.forward(years = 17, params.file = "WGTS/params.final", 
       fleets = data.frame(fleet = c("comm.act2", "comm.pas2", "comm.her", 
           "comm.spr"), ratio = c(0.7, 0.3, 0.2, 0.4)), effort = 1, 
       rec.scalar = data.frame(stock = rep(c("cod", "herring", "sprat"), 
           rep(ll, 3)), year = 2014:2030, rec.scalar = c(mult.cod, 
           mult.her, mult.spr)), rec.window = 2000:2012, num.trials = 1, 
       stochastic = F, custom.print = "printfile", compact = T)
```

**Comment by bthe** [comment]
The crux here is the use of `read.gadget.file` as it appears not be able to read the associated files for print. The switch `recursive` probably needs to be set to FALSE, see the latest commit.

**Comment by bthe** [comment]
btw, are you expecting `custom.print` to be a file or a string?

**Comment by vbartolino** [comment]
My intention was to read a file (ie a valid printfile provided by the user)
