### ISSUE TITLE
linearfleet and $fleet.info

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#56]
I've noticed that when 'linearfleet' is used, ```fit$fleet.info$amount``` reports the effort and not the catch as expected. I suspect that also other output ie ```fit$catchdist.fleets``` may have issues.

**Comment by bthe** [comment]
`gadget.fit` only reads on the `amount` file from the fleet file. The good thing is that this issue only affects the data in the fleet.info object, the output in catchdist.fleets only joins the likelihoodprinter output with the input data.

**Comment by bthe** [comment]
These are the same issues: https://github.com/Hafro/rgadget/issues/54
