### ISSUE TITLE
Forecast BAU and other F-based scenarios

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#57]
Does anyone have a suggestion on how to do forecasts based on predefined F levels (ie Fmsy). For instance in the ICES area this is relevant if we would like to test the current single species management into our multispecies models.

As I see it a first step would be to extend the function ```gadget.forward``` so that the arguments ```effort``` and/or ```fleet(ratio)``` could be specified for each year and possibly also timestep of the projection. This links to issue #26 

I'm currently quite stuck with this which is an urgent matter. Grateful for any help.

**Comment by bthe** [comment]
Are you talking about:
a) Running a forecast based on a single species harvest rate (or F) within Gadget
b) Want to use Gadget as an operating model for the single-species stock assessment models in a MSE fashion

**Comment by vbartolino** [comment]
First attempt here is to run BAU scenarios based on somehow fixed F

**Comment by bthe** [comment]
My suggestion would be to take last years harvest rate (or some average) and use that as the harvest rate for the BAU. If you want a feedback loop you are outside of the scope of gadget.forward
