### ISSUE TITLE
Confidence Intervals for Gadget estimates

### ISSUE THREAD

**Issue by niafall** [bthe/rgadget#58]
Is there a method in rgadget for calculating confidence intervals around gadget estimates (e.g. CI around the estimated catch fitted to a time-series, and for estimates of recruitment and F)?

**Comment by vbartolino** [comment]
This is very relevant topic that several would be interested to know more about.
Inspired by Bjarki's work (Elvarsson et al. 2014) my only very limited experience has been in exploring how spatial variability in ALK from a survey propagates into a single species Gadget model estimates. In practice I've fitted Gadget models on the bootstrap replicates of the ALK and calculated CI for the main stock statistics, accordingly.

**Comment by bthe** [comment]
@vbartolino is right, the suggested way of calculating the confidence intervals is by using some sort of bootstrap to propagate the data uncertainty through the model. I'm a bit biased towards using the spatial bootstrap described by Elvarsson et. al (2014), but the whaling comission do something similar with simulating the data inputs.
