### ISSUE TITLE
gadgetfile - duplicate entries

### ISSUE THREAD

**Issue by bthe** [bthe/rgadget#59]
When reading a fleet file of the form:
```
[fleetcomponent]
totalfleet      igfs
livesonareas    1
multiplicative  1
suitability
lingimm function        exponentiall50  #ling.igfs.alpha        #ling.igfs.l50
lingmat function        exponentiall50  #ling.igfs.alpha        #ling.igfs.l50
amount  three_fleets/Data/fleet.igfs.data
```
writing this out results in:
```
[fleetcomponent]
totalfleet      igfs
livesonareas    1
multiplicative  1
suitability
suitability     
lingimm function        exponentiall50  #ling.igfs.alpha        #ling.igfs.l50
lingmat function        exponentiall50  #ling.igfs.alpha        #ling.igfs.l50
amount  three_fleets/Data/fleet.igfs.data
```
I.e. the line containing `suitability`is duplicated.

**Comment by lentinj** [comment]
Have you specified ``file_type = "fleet"`` when reading with ``read.gadget.file``? Without you'll get the above.

**Comment by bthe** [comment]
This is actually quite weird, here is a small example that replicates this:
```
gd <- gadget_directory('test')

igfs.landings <- 
  structure(data.frame(year=defaults$year,step=1,area=1,number=1),
            area_group = mfdb_group(`1` = 1))


## write to file
gadgetfleet('Modelfiles/fleet',gd$dir,missingOkay = TRUE) %>% 
  gadget_update('totalfleet',
                name = 'igfs',
                suitability = paste0('\n',
                                     paste(c('lingimm','lingmat'),
                                           'function','exponentiall50',
                                           '#ling.igfs.alpha','#ling.igfs.l50',
                                           collapse='\n')),
                data = igfs.landings) %>% 
  write.gadget.file(gd$dir)

read.gadget.file(gd$dir,'Modelfiles/fleet')
gadgetfleet('Modelfiles/fleet',gd$dir,missingOkay = TRUE)
```

and it seems that the suitability gets replicated when the file_type is specified as `gadgetfleet` is just a wrapper around the `read.gadget.file`,

**Comment by bthe** [comment]
Setting the file_type to NULL appears to prevent this problem, not sure why though. But then updating gadgetfleet objects does not update the main file.

**Comment by bthe** [comment]
Hmm the crux of the problem is that there is a space right after "suitability". Adding:
```
line <- stringr::str_trim(line) 
match <- extract("([a-zA-Z0-9\\-_]*)\\s*([^;]*);?\\s*(.*)", line)
```
seems to work, but I assume the regex sentence can be fixed as well. See https://github.com/Hafro/rgadget/commit/057e0bbc969ba05c005ae6fc7e1291250d1d687a

**Comment by lentinj** [comment]
You're right, the "\t" is the key. With it it's considered a "key\tvalue" line. Without it it's considered a sub-component of the ``[fleetcomponent]``. So the problem isn't on read, rather on write since it's not realising that suitability is a subsection.

The good news is the real solution is to not worry about all that nonsense, and let the gadgetfile stuff handle the formatting for you:

```
gadgetfleet('Modelfiles/fleet',gd$dir,missingOkay = TRUE) %>%
  gadget_update('totalfleet',
                name = 'igfs',
                suitability = list(
                    lingimm = "function        exponentiall50  #ling.igfs.alpha        #ling.igfs.l50",
                    lingmat = "function        exponentiall50  #ling.igfs.alpha        #ling.igfs.l50"
                ),
                data = igfs.landings) %>%
  write.gadget.file(gd$dir)
```

**Comment by bthe** [comment]
This pull request actually reintroduces the my problem, as I'm using the `gadgetfleet` command to edit an existing model, via the model variant functionality.

**Comment by lentinj** [comment]
So really they need the spaces removed from the files on disk. How many do you have? Is editing the existing models by hand an option or are there loads at this point?

**Comment by bthe** [comment]
Well currently not many, e.g. see https://github.com/fishvice/gadget-models/blob/master/06-ling/00-setup/setup-three_fleets.R, but I'm working on a re-write of `gadget.forward` where I will rely on being able to read and edit valid fleet- and stock-files.
