### ISSUE TITLE
gamma suitability

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#6]
I believe there's a small bug in the suitability function.

The code is:
    else if (tolower(type) == "gamma") {
        S <- array(rep((l/((params[1] - 1) \* params[2] \* params[3]))^(params[1] - 
            1) \* exp(params[1] - 1 - 1/(params[2] \* params[3])), 
            each = length(L)), c(length(L), length(l)))
    }

and I think it should be changed with:
    else if (tolower(type) == "gamma") {
        S <- array(rep((l/((params[1] - 1) \* params[2] \* params[3]))^(params[1] - 
            1) \* exp(params[1] - 1 - l/(params[2] \* params[3])), 
            each = length(L)), c(length(L), length(l)))
    }

I'm using Rgadget_0.1

**Comment by bthe** [comment]
Well spotted, this has been corrected:)
