### ISSUE TITLE
recsigma in gadget.skeleton

### ISSUE THREAD

**Issue by pfrater** [bthe/rgadget#60]
Is there a reason why a recsigma object is created only when the minage of a stock is >0 (see code below)? I always seem to have problems with these lines of code anyways, but wondering why it is not well supported to have a minage of 0 when doesrenew == 1?

``` r
if (length(x$sigma) == 1) {
            x$sigma <- rep(x$sigma, length(x$minage:x$maxage))
        }
        else if (length(x$sigma) >= x$maxage & x$minage > 0) {
            recsigma <- x$sigma[1]
            x$sigma <- x$sigma[x$minage:x$maxage]
        }
        else if (length(x$sigma) > length(x$minage:x$maxage)) {
            x$sigma <- x$sigma[1:length(x$minage:x$maxage)]
        }
        else {
            stop("Error -- initial sigma useless")
        }
```

**Comment by bthe** [comment]
Well not really, this is a reasonable assumption when dealing with gadoid species as very little data is available (except in rare cases) on the 0 year olds. 

I would however suggest that you stop using gadget.skeleton function, as it will be deprecated. The way forward is the gadget_update functionality, e.g. see github.com/fishvice/gadget-models for example uses.
