### ISSUE TITLE
Fishing mortality in gadget.forward different from that estimated by gadget.fit

### ISSUE THREAD

**Issue by MarcoEnea** [bthe/rgadget#64]
I noticed that the values of fishing mortality in the historical (not forecasted) part extracted by gadget.forward() are different from those estimated by gadget.fit(). This does not happen when I provide a print.file disaggregated by age, but in this case there are problems with the forecasted future time series that shows a very little random variation.

**Comment by bthe** [comment]
This is actually an expected behavior as `gadget.fit` calculates the F according to a set age range whereas `gadget.forward` calculates the overall mortality for the stock (i.e. for all age groups).

**Comment by MarcoEnea** [comment]
The problem is that I want to create forecasts based on the F estimated as
in gadget.fit (that is by simply taking the mean of the F-at-age) for the
historical part.
So I modified the print.file in gadget.forward code by substituting the
string "age.agg" in the place of "allages.agg" in the predatorpreyprinter
component (not sure if this is correct).
In this way I'm able to obtain the desired mortality at age for the
historical part, but at the same time this procedure is not working for the
future forecasts, which are almost the same for each trial (no random
variation).

**Comment by bthe** [comment]
No, this is actually wrong. This printfile is used to calculate the total catch. You will need to create another printfile with the desired output. Not that there is no assessment error builtin so the effectively the fishing mortality should be fixed, only the catches should be stochastic.

**Comment by bthe** [comment]
You may find https://github.com/fishvice/gadget-models/blob/master/forward.R this useful. This is complete overhaul of the gadget.forward function, still work in progress though and depends on a couple of undocumented features in gadget.

**Comment by MarcoEnea** [comment]
Ok, many thanks for your advices. I'll look at the suggested script.
