### ISSUE TITLE
gadget.fit() not working when doesspawn==1

### ISSUE THREAD

**Issue by pfrater** [bthe/rgadget#66]
I am attempting to set up a gadget model with spawning instead of renewal for the recruitment; however, gadget.fit does not want to work with a spawning model. I think the issue is on line(s) 180-181 where `bio.by.year` gets merged with `stock.recruitment`.

```
# code above this creates the bio.by.year data.frame (lines 162-179)
   }) %>% dplyr::bind_rows() %>% dplyr::left_join(stock.recruitment %>% 
   dplyr::mutate(area = paste0("area", area), year = as.numeric(year)))
```
I'd like to rectify this issue by avoiding the left join with stock.recruitment (since there is no stock.recruitment data.frame in this instance). Is there a particular way that you'd like to see it done? or just any way that works.

Thanks,
Paul

**Comment by bthe** [comment]
I would simply have a check in the code for "missing" recruit process, as is done when merging the output with the compositional data.

**Comment by bthe** [comment]
This has been resolved.
