### ISSUE TITLE
multi-species gadget.fit error

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#68]
Hi,

I run gadget.iterative for my multi-species model. Everything works smoothly. Then I run gadget.fit(compile.fleet.info=FALSE) (since I'm using linearfleet for one species; for other two it's totalfleet). I got an error here: Error in names(len.agg)[1:3] <- c("length", "lower", "upper") : 
  attempt to set an attribute on NULL. However if I close the file with script, reopen it and only run gadget.fit(compile.fleet.info=FALSE) ( with weights being ready by previous step) I don't receive this error anymore.  Why can this happen? Thank you a lot in advance!

P.S. I have separate fleet files for three species.

With best wishes,
Nataliia

**Comment by bthe** [comment]
I guess this is has something to with open file connections, next time you encounter this could you try to run `closeAllConnections`?

**Comment by bthe** [comment]
I guess this has been resolved.
