### ISSUE TITLE
Uses "Depends" instead of "Imports" in DESCRIPTION

### ISSUE THREAD

**Issue by lentinj** [bthe/rgadget#7]
The only thing that ought be a "Depends" for any ~modern R package is the R versions you support, everything else ought be in "Imports".

The reason for this is that it adds the packages into the session's search path, potentially breaking other code (although I'm guessing it's making your life easier by loading all the packages you're using at the R prompt).

**Comment by bthe** [comment]
Yes this is just me being sloppy. To add to this the Rgadget code is littered with calls to function from plyr, dplyr and ggplot which ideally should be called directly using package::function.

**Comment by bthe** [comment]
In https://github.com/Hafro/rgadget/commit/329967f313fd89873ac33e8a089d58c080952854 I have cleaned up quite a lot of this sloppiness.
