### ISSUE TITLE
F problem with multispecies gadget.fit

### ISSUE THREAD

**Issue by niafall** [bthe/rgadget#71]
Using the latest commit of rgadget (1d0d3bc), gadget.fit is only calculating F (in res.by.year) for one of the three species. The other two species have NaN. This was not occurring in the previous version I had installed (42d0432).

The following warning is returned when gadget.fit is run:

```
Joining, by = c("stock", "year", "area")
Warning message:
Too many values at 30096 locations: 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, ...
```

In addition, the out.fit element of the gadget.fit list is not being appended or is lost somehow.

**Comment by niafall** [comment]
In addition, the out.fit element of the gadget.fit list is not being appended or is lost somehow.

**Comment by pfrater** [comment]
I believe this was an error in `gadget.fit` computing f.age.range. Should be fixed in pull request https://github.com/Hafro/rgadget/pull/72 at commit https://github.com/Hafro/rgadget/pull/72/commits/c2cc064e6c1a787380f4912a66ee81b812d13714

**Comment by pfrater** [comment]
Also, the weird warning message comes from when `gadget.fit` is trying to separate out the stocks within the `predatorpreyprinter` file. The predator and prey names in `fit$predator.prey` (i.e. `fit$predator.prey$predator` and `fit$predator.prey$prey` in this particular instance are not likely accurate.

**Comment by bthe** [comment]
@pfrater could you elaborate on the warning you get? Does my latest commit fix this?

Regarding the F calculation, the default is to calculate the apical F. When this is calculated in a multispecies context where you have different maximum ages, the code did not allow for varying ages. The most recent update should fix this.

**Comment by pfrater** [comment]
> @pfrater could you elaborate on the warning you get? Does my latest commit fix this?

On the [predator.prey](https://github.com/Hafro/rgadget/blob/master/R/gadgetfit.R#L133-L138) lines of `gadget.fit` the stock name is parsed to get the predator and prey names using `tidyr::separate(stock, c("prey", "tmp", "predator")`, but in Niall's model he has some stocks that are named using more than the `<prey>.prey.<predator>` convention (i.e. cod.prey.cod.dis); therefore the `separate` function was spitting a warning at those lines that there are more "names" than it knows what to do with. I assume `separate` just drops the last one (i.e. `.dis` in this case), but I don't know for sure.

**Comment by bthe** [comment]
Ok, my last commit should solve this issue.
