### ISSUE TITLE
gadget.fit problem with Ricker spawning model

### ISSUE THREAD

**Issue by niafall** [bthe/rgadget#74]
I'm trying to run `gadget.fit` with a model where `doesspawn==1` with a Ricker model.

The function is returning an error:

```
Warning messages:
1: In file(con, "r") : cannot open file '0': No such file or directory
2: In file(con, "r") : cannot open file '0': No such file or directory
```

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS
Rgadget_0.5
```

Is anyone else experiencing similar issues?

Niall

**Comment by pfrater** [comment]
This is a slight bug within `get.gadget.growth()`, which is called within `gadget.fit`. I don't think it actually affects anything, rather just an indexing issue within the function. Nonetheless, it is something that should get addressed and corrected. I've had it on my to-do list for a few months now...just haven't gotten to it before other priorities.

**Comment by niafall** [comment]
Thanks @pfrater

**Comment by bthe** [comment]
This is a general issue with `read.gadget.stockfile`, the proper way forward is to use the `gadget_file` functionality for the stock files.
