### ISSUE TITLE
using cv 

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#80]
Hi,

In my model survey indices for age0 sprat are overfitted (I'm using fixedslopeloglinearfit with slope 1):

![sprat_si](https://user-images.githubusercontent.com/16099366/32884574-1786aae8-cabb-11e7-97bb-466eca0baccb.png)

I am considering to use cv in gadget.iterative as its description says that it prevents survey indicies from overfitting.

My question is what does the value we assign to cv.floor mean? I've seen that Bjarki used 0.05 in one of examples. Does it mean that we allow model estimates of survey indicies to deviate by 5% in that case?

With best wishes,
Nataliia

**Comment by bthe** [comment]
The `cv.floor` argument gives the minimum inverse weight to a survey index, or just the minimum residual variance. So in your case, you can set the minimum minimum variance as the CV^2.
