### ISSUE TITLE
fit$sidat acoustic observed values are missing after update 

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#81]
After update acoustic in fit$sidat misses the observed value:

After update:
![selection_026](https://user-images.githubusercontent.com/16099366/33120752-4dbacea2-cf73-11e7-931b-57efa9c7ff28.png)

Before update:
![selection_027](https://user-images.githubusercontent.com/16099366/33120751-4cade6e8-cf73-11e7-9e7a-85c3fa920fc0.png)

**Comment by bthe** [comment]
There was a small typo in the read function, this is now fixed.
