### ISSUE TITLE
issue with fit$fleet.info after update

### ISSUE THREAD

**Issue by nataliia-kulatska** [bthe/rgadget#82]
Hi,

I noticed an issue with fit$fleet.info after update:

- harvestable biomass  and so harvest rate is NaN in fit$fleet.info. And we need harvest rate for projections

I haven't updated for quite a while before. So the version in which fleet.info was working for me might be something like: https://github.com/Hafro/rgadget/blob/f7d248c1d18ca8cb488097309c6ffd7271da93b6/R/gadgetFileIO.R

**Comment by bthe** [comment]
Looking at the Baltic_13.3 model, `gadget.fit` produces `NaN`s only for fleets with no catch in that time step, e.g. surveys, which is an expected behavior. Does this occur for other fleets in your model?
