### ISSUE TITLE
example of S-R in gadget.forward 

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#83]
Has anyone run ```gadget.forward``` with the argument ```prj.func``` specified for Ricker, Beverton-Holt or segmented regression and is keen to share an example?
Thank you in advance

**Comment by bthe** [comment]
This feature is not really useful for these types of projections. The idea behind this function is to deal with projections where recruitment is a function of external variables (e.g. temperature). There is a complete rewrite of gadget.forward in the works, you can see an example of it here: https://github.com/fishvice/gadget-models/blob/wkicemse/forwardling.R 
where a hockey stick model for the S-R is implemented.
