### ISSUE TITLE
gadget.iterative with -parallel

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#85]
Is it possible to use the new optimizers from the -parallel option with gadget.iterative?

**Comment by bthe** [comment]
Yes, but I guess you would need to set the run.serial argument as TRUE an make sure that the new gadget binary is in the path/reachable by callGadget.

**Comment by bthe** [comment]
Sorry, hadn't realized the need for the `-parallel` switch being passed through to callGadget. The relevant functions have been updated, would you mind giving it a spin?

**Comment by vbartolino** [comment]
I haven't tried in ```gadget.iterative```, but when I run ```callGadget``` I get the following error:

```
> fit <- callGadget(l=1, i="params.base", opt="optinfofile", gadget.exe="./gadget_openMP", parallel=TRUE)
Warning message:
In system(run.string, intern = TRUE, ignore.stderr = ignore.stderr) :
  running command './gadget_openMP -l     -i params.base -opt optinfofile          -parallel 2>/dev/null' had status 1
```
In a terminal the argument ```-parallel``` works but I need to specify ```-parallel spe``` otherwise it doesn't work. Might that be the reason?

**Comment by bthe** [comment]
Try `parallel='sep'`

**Comment by bthe** [comment]
This https://github.com/Hafro/rgadget/commit/0b78a6585b139a2ef92cc2f70b0032db76007d18 should fix this..

**Comment by bthe** [comment]
Sorry my bad, it is `parallel='spe'` not `'sep'`

**Comment by vbartolino** [comment]
of course I should have noticed...
Yes, it works! Thanks
