### ISSUE TITLE
plot fit of indices

### ISSUE THREAD

**Issue by vbartolino** [bthe/rgadget#89]
I've noticed that
`plot(fit, data="sidat", type="x-y")`
shows the observed vs predicted indices in their natural scale, even if a loglinearfit is used.
As a default I would suggest to use the log-log scale for this plot when this is specified in fittype

**Comment by bthe** [comment]
A quick fix for the problem is to do 
```
plot(fit,type='x-y') + scale_x_log10() + scale_y_log10()
```
I'll think about a more generic solution:)
