### ISSUE TITLE
Error when run gadget.fit

### ISSUE THREAD

**Issue by GeoTuxMan** [bthe/rgadget#9]
Hello !

When I run:
fit <- gadget.fit()
for whiting I get the error:
Error in data.frame(name = x, pos = pos, ord = regexpr(x, text[pos])[1],  : 
  arguments imply differing number of rows: 1, 0

So, I can't figure out what is the issue.

Thanks very much !

**Comment by bthe** [comment]
The command you entered assumes you have completed an iterative reweigthing run and the files in WGTS are all well formed. This particular error arises when a particular model likelihood component is not detected in the weighting results from the WGTS folder. The package has been updated to issue more descriptive error when this occurs.

If you just want to look at the fit for a specific parameter file you can do the following:

> fit <- gadget.fit(params.file='params.base',wgts=NULL)
