### ISSUE TITLE
callGadget returns status 309

### ISSUE THREAD

**Issue by mingsun** [bthe/rgadget#91]
I am following the tutorials for Rgadget from: https://heima.hafro.is/~bthe/getting_started.html.

When I run the code from the last section "starting a simulation", I get the warning as: "running command 'gadget-master/gadget.exe  -s      -main main      -log simple_log   ' had status 309 ".

There were also no new files generated.  I have put the executable "gadget.exe" under the working directory as well.

I just cannot figure out what went wrong.

**Comment by bthe** [comment]
Running `gadget` on windows is always a bit of hassle, mainly due to different line-endings conventions between windows and *nix based system. To tease this out could you try the following (assuming you have installed Rtools on windows):

* Update `gadget` and `rgadget` to the newest version

```
devtools::install_github('hafro/gadget2')
devtools::install_github('hafro/rgadget')
```

* Test the if you can run the example gadget model that comes with Rgadget:

```
system.file('extdata', 'cod_model.tgz', package = 'Rgadget') %>% 
  untar(exdir = path.expand('./gadget_example/'))

## change the working directory to the location of the gadget model
setwd('gadget_example/cod_model')

callGadget(s=1, i = 'WGTS/params.final', log = 'logfile')
```

If this fails I would suggest you try to run it on linux/macosx.

**Comment by mingsun** [comment]
> Running `gadget` on windows is always a bit of hassle, mainly due to different line-endings conventions between windows and *nix based system. To tease this out could you try the following (assuming you have installed Rtools on windows):
> 
> * Update `gadget` and `rgadget` to the newest version
> 
> ```
> devtools::install_github('hafro/gadget2')
> devtools::install_github('hafro/rgadget')
> ```
> 
> * Test the if you can run the example gadget model that comes with Rgadget:
> 
> ```
> system.file('extdata', 'cod_model.tgz', package = 'Rgadget') %>% 
>   untar(exdir = path.expand('./gadget_example/'))
> 
> ## change the working directory to the location of the gadget model
> setwd('gadget_example/cod_model')
> 
> callGadget(s=1, i = 'WGTS/params.final', log = 'logfile')
> ```
> 
> If this fails I would suggest you try to run it on linux/macosx.

Thank you bthe. I think something was wrong with the Rtools. I tried a different version of Rtools and it worked.
