### ISSUE TITLE
Writing stock initialconditions

### ISSUE THREAD

**Issue by lentinj** [bthe/rgadget#93]
This commit...

https://github.com/Hafro/rgadget/commit/1b18a6dcae100dbb7112414c16a0260c34c1eb16?w=1

Turns minage/length/dl/etc from being calculated from the numberfile, to being copies of the stock values (there's scope for being overriden by args, but it's dead code---you can't have anything other than ``number`` in args).

I suspect this is a C+P error, and guessing from the numberfile is what's wanted.

**Comment by bthe** [comment]
Well, there is two parts. First the age, I think it is best to infer the min and max age from the input data frame. For the lengths however the dl, min and max lengths cannot be derived from the data frame (unless you specify the `numberfile` option that no-one uses) so if are to specify these, they need to be set outside of the data frame. However this is an option that hardly anyone uses.
