### ISSUE TITLE
CMD check compliance

### ISSUE THREAD

**Issue by lentinj** [bthe/rgadget#96]
I've done a good chunk of sorting out the errors but @bthe you'll have to do some of what appears, not because they're tricky, but it'll be far faster for you to test the changes than me and/or know if something isn't really used now.

I've got a Makefile I generally use for rebuilding RCpp/Roxygen/tarball then running check, I can commit it if it's useful but if you live within Rstudio there'll be other ways of doing it.

I've got a long train ride at the weekend which will be a good opportunity to slog through the ``gadget_*_component`` documentation.

The most thorny problem is it moans that ``plot.gadget.fit`` and ``plot.gadget.ypr`` aren't compatible with the ``plot`` S3 method. It shouldn't match as far as I know---it's an unfortunate function name clash.

**Comment by bthe** [comment]
This has taken me a trip down memory lane, quite a lot of code from my early days of my phd that should be remove or stored else where. I've gone through many of the complaints listed in build checks, but it gives me a bunch of warnings related to the non-standard way tidyverse references variables that I don't know how to deal with. 

Regarding the plot functions, it is bit unfortunate, we could simply change the name to gadget_plot as I don't think we want to change the input to the functions. But this will cause all kinds of issues with the users.

**Comment by bthe** [comment]
Apparently typing .data$variable instead of variable solves the issue with tidyverse function checks:  https://community.rstudio.com/t/how-to-solve-no-visible-binding-for-global-variable-note/28887

**Comment by bthe** [comment]
Right, I'll leave it to you sort out the other remaining issues, will continue to clear the S4 crud from the package in the next few days, but that will require full rewrite of `gadget.forward` and `gadget.ypr` which I am currently working on.

**Comment by lentinj** [comment]
We're down to 2 NOTES with ``check --as-cran``. We could remove 1 by removing the example simulation run, but I'd rather leave it there until we have to remove it. The other states that gadget2 / mfdb aren't on CRAN, but we know that :)
